#!/bin/bash

if [ $# -le 1 ]
then
    echo "Usage: $0 [REMOTE PATH] [COMMAND]"
    exit 1
fi

WD=`pwd`
ROOT=$WD
while [ ! -f "$ROOT/.aya" ]
do
  if [ "$ROOT" = "/" ]
  then
      echo "Error: no .aya found in any parent directory of $WD."
      exit 1
  fi

  ROOT=`dirname $ROOT`
done

WHERE=$1
shift
WHAT=$*
RELATIVE_WD=${WD:${#ROOT}}
HOSTINFO=( `echo "$WHERE" | tr ":" "\n"` )
HOST=${HOSTINFO[0]}
REMOTE_SUBDIR=`basename "$ROOT"`
REMOTE_PATH="${HOSTINFO[1]}/$REMOTE_SUBDIR"

rsync -a --exclude-from="$ROOT/.aya" "$ROOT" "$WHERE" && \
  ssh "$HOST" "cd \"$REMOTE_PATH/$RELATIVE_WD\" && $WHAT"